Fix undefined reference to __gxx_personality_v0 link errors (#114)
* Fix undefined reference to __gxx_personality_v0 link errors

* Try adding to CXX flags

* Revert "Try adding to CXX flags"

This reverts commit b5d5d0f3127e5ce801e1706113cbdd882896fff8.